// GCSE History Configuration
// Generated from top_200_exam_universe_seed.csv

export const EXAM_CONFIG = {
  examId: "EXAM193",
  slug: "gcse-history",
  name: "GCSE History",
  fullName: "GCSE History",
  alias: "GCSE History",
  family: "GCSE",
  category: "School exams",
  subcategory: "Subject exam",
  country: "United Kingdom",
  region: "EMEA",
  languages: ["English"],
  estimatedAnnualTakers: "high",
  testingWindow: "May-Jun",
  schedulePattern: "Annual",
  ageGroup: "14-16",
  targetUser: "School student",
  delivery: "Paper-based",
  questionTypes: ["Short answer + essays"],
  adaptivity: "Linear",
  sections: "2-3 papers",
  scoringMode: "Grade 1-9",
  essayOrSpeaking: "Essay",
  ipRisk: "Low",
  contentReuse: "history_civics",
  uiEngine: "paper_essay",
  monetizationPotential: "Medium",
  tier: "Tier 5",
  launchWave: "Wave 7",
  themeColor: "#D97706",
  themeColorDark: "#B45309",
  localizationComplexity: "Low",
  offlineNeeded: true,
  mobileFirst: true,
  locale: "en",
  isRTL: false,
  freemiumGate: {
    dailyQuestions: 10,
  },
} as const;

export type ExamConfig = typeof EXAM_CONFIG;
